---
- name: Setup NixOS Package Manager for servers (experiment)
  hosts: all
  become: true
  tasks:

    - name: Ensure curl is installed
      apt:
        name: curl
        state: present
      when: ansible_facts['pkg_mgr'] == 'apt'

    - name: Ensure curl is installed
      yum:
        name: curl
        state: present
      when: ansible_facts['pkg_mgr'] == 'yum'

    - name: Install Nix package manager
      shell: |
        sh <(curl -L https://nixos.org/nix/install) --daemon
      args:
        creates: /nix/var/nix/profiles/default

    - name: Source nix profile for current session
      lineinfile:
        path: /etc/profile
        line: ". /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh"
        state: present
      notify: Reload profile

    - name: Create nix group and add users
      user:
        name: "{{ item }}"
        groups: nix-users
        append: yes
      loop: "{{ ansible_users | default([ansible_env.USER]) }}"
      when: ansible_users is defined

  handlers:
    - name: Reload profile
      shell: source /etc/profile
      become: false
