---
- name: Setup Terraform
  hosts: all
  become: yes
  tasks:
    - name: Install dependencies
      package:
        name: 
          - unzip
          - curl
        state: present

    - name: Download Terraform binary
      get_url:
        url: "https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip"
        dest: "/tmp/terraform.zip"

    - name: Extract Terraform binary
      unarchive:
        src: "/tmp/terraform.zip"
        dest: "/usr/local/bin/"
        remote_src: yes

    - name: Set executable permissions for Terraform
      file:
        path: /usr/local/bin/terraform
        mode: '0755'
        state: file

    - name: Verify Terraform installation
      command: terraform --version
      register: terraform_version

    - name: Display Terraform version
      debug:
        msg: "Terraform installed: {{ terraform_version.stdout }}"
