---
- name: Setup Python Environment
  hosts: all
  become: yes
  tasks:
    - name: Install Python and pip
      package:
        name: 
          - python3
          - python3-pip
        state: present

    - name: Ensure virtualenv is installed
      pip:
        name: virtualenv

    - name: Create a Python virtual environment
      command: virtualenv /opt/myenv
      args:
        creates: /opt/myenv

    - name: Install required Python packages
      pip:
        requirements: /path/to/requirements.txt
        virtualenv: /opt/myenv
